on:
  push:
    branches:
    - master
  release:
    types: [ prereleased, released]

jobs:
  publish:
    name: 拡張機能を公開_vsCode
    runs-on: windows-latest
    # if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: Nodeをインストール
        uses: actions/setup-node@v3
      - name: node_modulesのインストール
        run: npm install
      - name: 拡張機能を公開
        run: |
          npm run deploy
        env:
          VSCE_PAT: ${{secrets.VSCE_PAT}}