name: vsceデプロイ
run-name: vsceへの公開:${{ github.ref }}
on:
  push:
    branches:
    - master
  release:
    types: [ prereleased, released]

jobs:
  publish:
    name: vsceデプロイ
    runs-on: windows-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: Nodeをインストール
        uses: actions/setup-node@v3
      - name: node_modulesのインストール
        run: npm install
      - name: ttsサービスのファイル削除
        run: |
          Get-ChildItem "${{github.workspace}}\bin\*.*" -exclude docs |Remove-Item
      - name: ttsサービスのzipファイルをダウンロード
        run: |
          gh release download --repo simanasch/SpeechGRpcServer v0.0.1 -D "${{ github.workspace }}\bin" -p *.zip
        env:
          GH_TOKEN: ${{secrets.READ_SPEECHGRPCSERVER}}
      - name: ttsサービスをzipから解凍
        run: |
          7z x  "${{ github.workspace }}\bin\*.zip"  -o"${{ github.workspace }}\bin" -aoa
      - name: 拡張機能を公開
        run: |
          npm run deploy
        env:
          VSCE_PAT: ${{secrets.VSCE_PAT}}
      - name: 拡張機能のパッケージを作成
        run: vsce package
      - name: ビルド内容を保存
        uses: actions/upload-artifact@v3
        with:
          name: vscePackage
          path: ./*.vsix