on:
  # push:
  #   branches:
  #   - main
  release:
    types: [published]

jobs:
  publish:
    name: 拡張機能を公開(vsCode)
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Publish vsCodeTalker
        run: |
          npm run vscode:prepublish
          npm run deploy
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_PAT }}