name: 拡張機能のビルド、デプロイ
run-name: build:${{ github.ref }}
on:
  push:
    branches:
    - master
    - develop
  release:
    types: [ prereleased, released]

jobs:
  build:
    name: 拡張機能のビルド
    runs-on: windows-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
      - name: Nodeをインストール
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: node_modulesのインストール
        run: npm ci
      - name: ttsサービスのファイル削除
        run: |
          Get-ChildItem "${{github.workspace}}\bin\*.*" -exclude docs |Remove-Item
      - name: ttsサービスのzipファイルをダウンロード
        run: |
          # バージョン指定なしの場合、最新のリリースを取得する
          gh release download --repo simanasch/vsCodeTalkerLanguageServer  -D "${{ github.workspace }}\bin" -p *.zip
        env:
          GH_TOKEN: ${{secrets.READ_SPEECHGRPCSERVER}}
      - name: ttsサービスをzipから解凍
        run: |
          7z x  "${{ github.workspace }}\bin\*.zip"  -o"${{ github.workspace }}\bin" -aoa
      - name: 拡張機能のパッケージを作成
        run: npm run package
      - name: ビルド内容を保存
        uses: actions/upload-artifact@v3
        with:
          name: vscePackage
          path: ./*.vsix
      - name: 拡張機能を公開
        # 当面masterにpushした時だけ動かす
        if: ${{ github.ref_name == 'master' && github.event_name == 'push' }}
        run: |
          npm run deploy
        env:
          VSCE_PAT: ${{secrets.VSCE_PAT}}